version: '3'
services:
  app:
    build: ./challenge2
    ports:
      - "8080:8080"
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./challenge2/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
